### ISSUE TITLE
Cannot install plugin

### ISSUE THREAD

**Issue by jmtrivial** [kauevestena/osm_sidewalkreator#1]
Dear kaeuvestena,

I tried to install osm_sidewalkreator following these steps:
* install pb_tool (via pip)
* run ```pb_tool compile```
* run ```pb_tool zip```
* run QGIS and tried to install the plugin using the generated zip file.

Here is the error I obtain. Should I install something else that corresponds to ```osm_fetch```?

```
Impossible de charger l'extension 'osm_sidewalkreator' provoque une erreur lors de l'appel à sa méthode classFactory() 


ModuleNotFoundError: No module named 'osm_sidewalkreator.osm_fetch' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 335, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/jm/.local/share/QGIS/QGIS3/profiles/default/python/plugins/osm_sidewalkreator/__init__.py", line 35, in classFactory
    from .osm_sidewalkreator import sidewalkreator
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/jm/.local/share/QGIS/QGIS3/profiles/default/python/plugins/osm_sidewalkreator/osm_sidewalkreator.py", line 82, in 
    from .osm_fetch import *
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'osm_sidewalkreator.osm_fetch'


Version de Python : 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110] 
Version de QGIS : 3.20.1-Odense Odense, 2755615b9f 

Chemin Python :
/usr/share/qgis/python
/home/jm/.local/share/QGIS/QGIS3/profiles/default/python
/home/jm/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python39.zip
/usr/lib/python3.9
/usr/lib/python3.9/lib-dynload
/home/jm/.local/lib/python3.9/site-packages
/usr/local/lib/python3.9/dist-packages
/usr/local/lib/python3.9/dist-packages/launchpad_py-0.9.1-py3.9.egg
/usr/lib/python3/dist-packages
/usr/lib/python3.9/dist-packages
/home/jm/.local/share/QGIS/QGIS3/profiles/default/python
```

I'm using a debian testing, with QGIS 3.20 from the repository https://qgis.org/debian

Thank you in advance!

**Comment by kauevestena** [comment]
Hello Jean Marie!! The Plugin still a work in progress...

You may try to simply put the entire project folder on the plugins folder of your QGIS installation, you can find it at:

     Settings -> User profiles -> Open active profile folder

and then activate the plugin at plugin manager at "installed" tab

all the binaries should be precompiled, at this point I even not checked the installation in another machine...

**Comment by NyakudyaA** [comment]
@kauevestena Has this been resolved as well now that you officially publishing the plugin

**Comment by kauevestena** [comment]
> @kauevestena Has this been resolved as well now that you officially publishing the plugin

yeah, I have forgot to tell @jmtrivial that the installation at that point could be done loading a zipped version.

by now it has been solved.
