### ISSUE TITLE
[Feature Request] Allow user to choose tag for segment between kerb and sidewalk

### ISSUE THREAD

**Issue by natedx** [kauevestena/osm_sidewalkreator#13]
Hello @kauevestena,

First of all, what an amazing plugin ! I randomly fell upon your English demo on Youtube, and was blown away by your work !
The plugin works very well and with all the available parameters it only takes a bit of experimentation to get what you want. 

# The issue

In many regions the small footway segment which joins the crossing to the sidewalk is itself tagged as a sidewalk.
![Example](https://github.com/kauevestena/osm_sidewalkreator/assets/46789008/7158981d-96b6-4e23-8380-fae898cf9e0d)
However, in the generated crossings from SidewalKreator, this segment is always tagged as a crossing even though it is before the kerb and therefore by definition, on the sidewalk.

# Possible solution

It is of course possible to edit this in JOSM later, but for the sake of speed, it would be nice to be able to choose this tagging behavior.
Adding an opt-in toggle box for this could save a lot of time.

**Comment by kauevestena** [comment]
Hey man!! I'm so thrilled that you liked it!!

Well, that's quite strange behavior according to the way it's implemented,

Can you send me an screenshot of the parameters and if don't mind a bounding box or, even better, a wkt in order for me to reproduce it and address the issue?

Sorry for the delay, I'm attending FOSS4G conference, then I'm quite focused here, but for sure I'll solve the issue!

**Comment by natedx** [comment]
Hello !
Sorry for the misunderstanding, SidewalkKreator is working as intended ! 
This is actually a feature request to implement the tagging behavior shown in my screenshot, that is the convention in my area. I will edit the title !
To rephrase, I think it would be a good idea to be able to choose the tag (crossing or sidewalk) of the small way that links the kerb to the sidewalk. In my usage, I would choose "sidewalk", but right now, SidewalKreator tags it as a "crossing". This would save me a lot of time when adjusting everything in JOSM.

As a side note, this implies that this small portion is now it's own separate way.

Here is a screenshot of my desired tagging behavior : 
<img width="991" alt="Capture d’écran 2023-06-29 à 12 14 32" src="https://github.com/kauevestena/osm_sidewalkreator/assets/46789008/79fb2731-ebb6-4d6a-b055-6ee3a4003d95">

**Comment by kauevestena** [comment]
@natedx Sorry again for the delay, man, I was returning home from the conference.

Well, I'll try to implement this feature, but I'm still in a hurry with many stuff, so I'll try to address this in the next 15 days, although I found that variation of the schema quite uncanny, If it's in use is valid to be contemplated!

**Comment by kauevestena** [comment]
@natedx let me know if you still need this feature!!

**Comment by natedx** [comment]
Hello @kauevestena ! Yes it would be very practical ! :)

**Comment by kauevestena** [comment]
Good news, man!! I've made this test release before I implement the GUI part, test it and tell me if everything went smoothly!!

It will create the modified output in the "auxiliary_files" folder, named as "sidewalkreator_output_alt_scheme.geojson"

Enjoy!!


[osm_sidewalkreator.zip](https://github.com/kauevestena/osm_sidewalkreator/files/13199592/osm_sidewalkreator.zip)


ZIP installation instructions:

plugins > manage and istall plugins... > install from ZIP

then use the "..." button to browse the file, accept the warning and the plugin should be installed!

**Comment by natedx** [comment]
Hello ! Just finished a test run, it seems to be working great ! Thanks a lot for the feature :)

![Capture d’écran 2023-10-30 à 11 59 53](https://github.com/kauevestena/osm_sidewalkreator/assets/46789008/238c44e4-63e7-4b97-8abb-677188d54181)

**Comment by kauevestena** [comment]
That's so nice to hear! I will package and update the QGIS plugin version!

**Comment by kauevestena** [comment]
hey @natedx do you know if this alternate schema is documented somewhere? I'm thinking of putting a checkbox on the exporting part, with a link it would be great for the user to understand.

**Comment by natedx** [comment]
Hello, here's what I have found on the OSM wiki : https://wiki.openstreetmap.org/wiki/Key:crossing#Additional_tags

**Comment by kauevestena** [comment]
Great,  thanks a lot @natedx!
