### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [kauevestena/osm_sidewalkreator#2]
# Problem

Please fix the plugin homepage link. It currently points to https://github.com/kauevestena/osm_sidewalkreator/wiki

**Comment by kauevestena** [comment]
Changed to https://github.com/kauevestena/osm_sidewalkreator right now, anything else?

**Comment by NyakudyaA** [comment]
@kauevestena This hasn't been changed yet on the plugin homepage. Can you please update the plugin on plugins so that I can approve

**Comment by kauevestena** [comment]
> @kauevestena This hasn't been changed yet on the plugin homepage. Can you please update the plugin on plugins so that I can approve

Sorry @NyakudyaA originally the "wiki" was meant to be a sort of homepage, I have updated the plugin version, but I've forgot to change that point I will upload the plugin again

**Comment by kauevestena** [comment]
@NyakudyaA done uploading a new version!! Can you aprove it?
