### ISSUE TITLE
How to try it for a new city (Leeds)?

### ISSUE THREAD

**Issue by Robinlovelace** [kauevestena/osm_sidewalkreator#3]
I would like to use this for our openinfra project: https://github.com/udsleeds/openinfra

Our main case study city is Leeds, make sense to test out your methods for our city? Happy to try to reproduce the findings!

**Comment by kauevestena** [comment]
Hello Robin!! Thank you for the interest on using the plugin!! Apologies for the late response, i was involved with the conferences 😅

Of course it can be used on Leeds! Yeah, it can be reproduced, the idea is of the plugin to contemplate the whole word!!

First of all, it's a huge city, so as like for other lots of cities the best way is to create the network of each borough, one by one, as long as the Overpass can't handle big requests and some processes inside the code can start to become heavy for a too big area (also as there were complex structures like bridges or so that the plugin can't handle in the current version).

You can add me on twitter where you can find me also as @kauevestena , send me a DM, and I will be glad to help you!

**Comment by Robinlovelace** [comment]
Hi @kauevestena many thanks for the offer of support. I will chat with colleagues and see if we can get something going, starting with a small area of the city.

**Comment by Robinlovelace** [comment]
Update here: I've found a source of existing sidewalk data but unfortunately it's not in the public domain and cannot be published. Tiny section of it shown below. I will see if I can map some of this with reference to satellite imagery only.

![image](https://user-images.githubusercontent.com/1825120/187085163-b3394671-152d-49f4-b209-cb01e0a005ef.png)

My guess, given this is available nationally but not in the public domain: explore options for getting this data out into the open.

**Comment by Robinlovelace** [comment]
Update, installing the plugin...

![image](https://user-images.githubusercontent.com/1825120/187085272-3a3f663b-d57a-4135-bb41-fde730214a16.png)

From the zip hosted here: https://plugins.qgis.org/plugins/osm_sidewalkreator/

**Comment by Robinlovelace** [comment]
And.. getting this cool interface!

![image](https://user-images.githubusercontent.com/1825120/187085350-696c945e-2a2a-401a-aea4-4546eae11a4b.png)

**Comment by Robinlovelace** [comment]
OK, clicked on a few buttons and not sure what to do next.. Will provide heads-up to colleagues James and Greta, who I think you met in Florence :tada: on ideas for next steps. Will be great if we can get sidewalks mapped with open data :pray:

**Comment by kauevestena** [comment]
It's so nice to get people acknowledging my work :'-)


> OK, clicked on a few buttons and not sure what to do next.. Will provide heads-up to colleagues James and Greta, who I think you met in Florence tada on ideas for next steps. Will be great if we can get sidewalks mapped with open data pray

You can follow my tutorials on the plugin usage:

This one is about the basics:
https://www.youtube.com/watch?v=jq-K3Ixx0IM

This one is a muted video (please watch listening to some music ^.^ ) documenting the importing process on JOSM, I will make a better one in the forthcoming weeks 
https://www.youtube.com/watch?v=Apqdb73lNvY

**Comment by Robinlovelace** [comment]
Many thanks for the replies, this is great! I have no time to work on it this week or perhaps even month but hope to. The links you share will help me and others when we get round to trying it out :pray:

**Comment by kauevestena** [comment]
Surely! In the next weeks I will work on a new release of the plugin, and probably more videos or tutorials!

**Comment by kauevestena** [comment]
@Robinlovelace I'm closing this issue as a one from a long time ago with the plugin still as an experimental one. Were you able to use it? Feel free to reopen or submit new issues!
