### ISSUE TITLE
Plugin crashes QGIS 3.26.3 on Debian

### ISSUE THREAD

**Issue by kresp0** [kauevestena/osm_sidewalkreator#4]
Hi, the plugin seems to install correctly but it crashes QGIS 3.26.3 on Debian.

```
$ qgis
/home/user/.local/share/QGIS/QGIS3/profiles/default/python/plugins/osm_sidewalkreator
QGIS died on signal 11Aborted
```
Running QGIS again will show this message:
`Plugin osm_sidewalkreator: This plugin is disabled because it previously crashed QGIS.`

Tried enabling and disabling all other plugins but osm_sidewalkreator still crashes every time. I can reproduce it with another user that on the same machine.

Previously tried to install the plugin on an older QGIS version (the one maintained by Debian) via zip, but that failed and that made me to uninstall QGIS and install it from the official repos. No idea if this is related.

Any ideas on what may be causing this issue? How can I get more debug information to find out?

```
QGIS version | 3.26.3-Buenos Aires | QGIS code revision | 65e4edfdad
Qt version | 5.15.2
Python version | 3.9.2
GDAL/OGR version | 3.2.2
PROJ version | 7.2.1
EPSG Registry database version | v10.008 (2020-12-16)
GEOS version | 3.9.0-CAPI-1.16.2
SQLite version | 3.34.1
PDAL version | 2.2.0
PostgreSQL client version | 13.8 (Debian 13.8-0+deb11u1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Debian GNU/Linux 11 (bullseye)

Active Python plugins
quick_map_services | 0.19.29
sagaprovider | 2.12.99
processing | 2.12.99
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
```

**Comment by kauevestena** [comment]
I think that was just the same at #6 

sadly QGIS does not come with shapely bundled, so installing it manually will solve the issue

     <qgis_python_path> -m pip install shapely 

I will add it to "known issues" at the readme

And I will try to use ogr2ogr directly in order to remove even this small dependency!

**Comment by kauevestena** [comment]
@kresp0 this issue came from a long time ago, I will close it, but feel free to reopen it!
