### ISSUE TITLE
Error after pressing "Clean OSM Data..." button

### ISSUE THREAD

**Issue by SeanWhitcomb** [kauevestena/osm_sidewalkreator#7]
I drew a polygon and used all the default settings. This is the error I get when I click the "Clean OSM Data and Compute Intersections" button: 
-----
An error has occurred while executing Python code: 

AttributeError: 'QgsFeature' object has no attribute 'attributeMap' 
Traceback (most recent call last):
  File "C:\Users/seana/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\osm_sidewalkreator\osm_sidewalkreator.py", line 517, in data_clean
    already_existing_sidewalks_list = select_feats_by_attr(self.clipped_reproj_datalayer,'footway','sidewalk')
  File "C:\Users/seana/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\osm_sidewalkreator\generic_functions.py", line 1198, in select_feats_by_attr
    if feature.attributeMap().get(attr) == value:
AttributeError: 'QgsFeature' object has no attribute 'attributeMap'

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.22.0-Białowieża Białowieża, d9022691f1 

Python Path:
C:/PROGRA~1/QGIS 3.22.0/apps/qgis/./python
C:/Users/seana/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/seana/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS 3.22.0/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.22.0\bin\python39.zip
C:\PROGRA~1\QGIS 3.22.0\apps\Python39\DLLs
C:\PROGRA~1\QGIS 3.22.0\apps\Python39\lib
C:\Program Files\QGIS 3.22.0\bin
C:\Users\seana\AppData\Roaming\Python\Python39\site-packages
C:\PROGRA~1\QGIS 3.22.0\apps\Python39
C:\PROGRA~1\QGIS 3.22.0\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS 3.22.0\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS 3.22.0\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS 3.22.0\apps\Python39\lib\site-packages\Pythonwin
C:/Users/seana/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\seana\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools
C:\Users\seana\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools
C:/Users/seana/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins/osm_sidewalkreator\dependencies/osm2geojson-0.1.33-py3-none-any.whl
C:\Users/seana/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web
C:\Users\seana\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins

**Comment by kauevestena** [comment]
https://www.qgis.org/pyqgis/3.24/core/QgsFeature.html?highlight=qgsfeature#qgis.core.QgsFeature.attributeMap

Looking at 3.24 documentation, at the attibuteMap method it says:
   
    New in version 3.22.2.

So it seems that is a matter of minor version updating, since your report says

     QGIS version: 3.22.0-Białowieża Białowieża, d9022691f1

Can you try to update your QGIS?

I will update the minimum required to 3.22.2 !!

**Comment by SeanWhitcomb** [comment]
That worked! I'm excited to start using this tool. We're missing a lot of sidewalks in my city.

**Comment by kauevestena** [comment]
If in doubt, please contact me!!
