### ISSUE TITLE
User Interface on QGIS Plugin

### ISSUE THREAD

**Issue by jakestenson** [kauevestena/osm_sidewalkreator#9]
When using the plugin on QGIS the interface is warped making it unusable. Not sure if I'm doing something wrong here?

![image](https://user-images.githubusercontent.com/123202598/213783150-886a1a0f-985e-4017-9226-e54094617ae0.png)

**Comment by kauevestena** [comment]
Hello @jakestenson , I've never seen anything like this before...

It seems an Operating System issue, which is your?

**Comment by jakestenson** [comment]
Hi,

Sorry I haven't used the plugin since

Jake

**Comment by kauevestena** [comment]
Oh, no worries! I'm closing the issue then, but feel free to open any other one at any moment!
